# version: '3.8'

services:
    client:
      build:
        context: ./client
        dockerfile: Dockerfile
      container_name: client
      depends_on:
        - server
      ports:
        - "3009:3000"
      volumes:
        - ./client:/app

    server:
      build:
        context: ./server
        dockerfile: Dockerfile
      container_name: server
      depends_on:
        - mysql
      ports: 
        - "3002:3001"
      volumes:
        - ./server:/app

    mysql:
      image: mysql:latest
      container_name: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: employee_db
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      ports:
        - "3306:3306"
      volumes:
        # - mysql_data:/var/lib/mysql  # Persistent data volume
        - ./mock_db:/docker-entrypoint-initdb.d # Optional: Mount a directory for initialization scripts

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: phpmyadmin
      restart: always
      environment:
        PMA_HOST: mysql
        # PMA_PORT: 3306
        MYSQL_ROOT_PASSWORD: rootpassword
      ports:
        - "8080:80"
      depends_on:
        - mysql

volumes:
  mysql_data:

  
